config/routes.rb
Hackatools::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  resources :products do 
    collection do
      get 'search'
      get 'tag/:tag', to: 'products#tag'
    end
    resources :reviews, except: [:show, :index]  
  end

  get "pages/about"
  get "pages/contact"
  get "pages/profile"

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	acts_as_ordered_taggable # Alias for acts_as_taggable_on :tags


	searchkick word_start: [:name]

	has_many :reviews

	has_many :watchlists
	has_many :users, through: :watchlists, source: :user

	validates :name, :website, presence: true
	validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
	  message: "must start with http:// or https://" }

	def avg_rating
		reviews = Review.where(product_id: self.id).order('created_at DESC')
    if reviews.blank?
      rating = 0
    else
      rating = reviews.average(:rating).round(2)
    end
    rating
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search, :tag]
  before_action :check_user, except: [:index, :show, :search, :tag]

  # GET /products
  # GET /products.json
  def index
    @new_products = Product.all.order('created_at DESC')
    @trending_products = Product.all.order('created_at ASC')
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
    @reviews = Review.where(product_id: @product.id).order('created_at DESC')
    @tags = @product.tag_list
    @similar_products = @product.find_related_tags
    if @reviews.blank?
      @ease_rating = 0
      @speed_rating = 0
      @avg_rating = 0
    else
      @ease_rating = @reviews.average(:ease_of_use_rating).round(2)
      @speed_rating = @reviews.average(:speed_of_dev_rating).round(2)
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    product_params['tag_list'] = format_tags(product_params['tag_list'])
    fail
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].present?
      @products = Product.search(params[:search], fields: [{name: :word_start}])
    else
      @products = Product.all
    end
  end

  def tag
    if params[:tag].present?
      @tag = CGI.unescape(params[:tag])
      @products = Product.tagged_with(@tag)
    else
      @tag = nil
      @product = Product.new
    end
  end

  private

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: 'Sorry, only admins can do that!'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def format_tags(tag_list)
      results = tag_list.split(/,/)
      return results.map {|result| result.strip }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :website, :description, :image, :tag_list)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => { multipart: true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation" class= "alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: 'Heroku' %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control", placeholder: 'http://www.heroku.com' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", placeholder: 'Heroku is a platform as a service (PaaS) that enables developers to build and run applications entirely in the cloud.' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_review_form.erb
<h3>Used <%= @product.name %> for a project? How was it?</h3>

<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>      
    </div>
  <% end %>
  <div class="jumbotron new-review-container">
    <div>Easy to master: <div class="rating-write__ease"></div>(learning curve?)</div>
    <br>
    <div>Creates fast: <div class="rating-write__speed"></div>(how fast does this tool do what you want?)</div>
    <br>
    <div class="form-group new-review-form">
      <%= f.text_area :comment, rows: '6', class: "form-control", id: "html", placeholder: 'Your review helps fellow developers learn more about this tool. How well it works and how much success you’ve had with it.' %>
    </div>
    <div>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/products/_review_list.html.erb
<% if @reviews.blank? %>
	<h3>No reviews yet. Be the first one to write one!</h3>
	<%= render 'review_form' %>
<% else  %>
	<div class="card-section new-review-placeholder">
		<div><div class="profile-pic" style="width: 60px;height:60px;border-radius:150px;background:#CCC;display:inline-block;"></div><div class="rating-write" style="display:inline-block;height:60px;line-height:60px;vertical-align:top;margin:0px 20px;"></div><span style="height:60px;line-height:65px;vertical-align:top;font-size:16px;font-weight:600;">Select your rating.</span></div>
	</div>
	<div class="review-list card-section">
		<table class="table">
			<thead>
				<tr>
					<th class="col-md-3">All Reviews (<%= @reviews.count %>)</th>
					<th class="col-md-9"></th>
				</tr>
			</thead>
			<tbody>
				<% @reviews.each do |review| %>
					<tr>
						<td>
							<h4><%= "#{review.user.email}" %></h4>
							<p><%= review.created_at.strftime('%-m/%-d/%-y') %></p>
						</td>
						<td>
							<div>
								<div class="rating-readonly" data-score=<%= review.rating %> ></div>
							</div>
							
							<br>
							<br>
							<p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
							<% if user_signed_in? %>
								<% if (review.user == current_user) || (current_user.admin?) %>
									<%= link_to 'Edit', edit_product_review_path(@product, review) %>
									<%= link_to 'Delete', product_review_path(@product, review), method: :delete %>
								<% end %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<%= render 'review_form' %>
<% end %>

app/views/products/_similar_products.html.erb
<div class="similar-products card-section">
	<h3>Similar Products: </h3>
	<% @similar_products.each do |product| %>
		<div class="media">
		  <div class="media-left">
		    <a href="#">
		      <img class="media-object" src=<%= product.image_url %> alt="...">
		    </a>
		  </div>
		  <div class="media-body">
		    <h4 class="media-heading"><%= product.name %></h4>
		    <br>
		    <div class="similar__stars-container">
		      <div class="review-rating" data-score=<%= product.avg_rating %> ></div> <div class="review-count"><%= "#{product.reviews.length} reviews" %></div>
		    </div>
		  </div>
		</div>
	<% end %>
</div>

app/views/products/edit.html.erb
<div class="container-fluid">
	<h1>Editing product</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @product, class: 'btn btn-link' %> |
	<%= link_to 'Back', products_path, class: 'btn btn-link' %>
</div>

app/views/products/index.html.erb
<div class ="jumbotron">
  <div class="container-fluid">
    <h3>HackATools is the best way to find reviews on development tools.</h3>
    <h4>Explore the favorite tools, frameworks and products in the software development world.
    <br>Leave reviews and ratings for your fellow hackers.</h4>
  </div>
</div>
<div class="container-fluid">
  <div class="product-category">
    <h3>Trending:</h3><%= link_to 'see more>>', search_products_path, class: 'see-more' %>
  </div>
  
  <div class="product-container">
    <% @trending_products.each do |product| %>
      <a href=<%= product_path(product) %> class="item">
        <div class="item__logo"><%= image_tag product.image_url %></div>
        <h4><%= product.name %></h4>
        <div class="stars-container">
          <div class="star-rating" data-score=<%= product.avg_rating %> ></div> <span><%= "#{product.reviews.length} reviews" %></span>
        </div>
      </a>
    <% end %>
  </div>
  <div class="product-category">
    <h3>Best New:</h3><%= link_to 'see more>>', search_products_path, class: 'see-more' %>
  </div>
  <div class="product-container">
    <% @new_products.each do |product| %>
      <a href=<%= product_path(product) %> class="item">
        <div class="item__logo"><%= image_tag product.image_url %></div>
        <h4><%= product.name %></h4>
        <div class="stars-container">
          <div class="star-rating" data-score=<%= product.avg_rating %> ></div> <span><%= "#{product.reviews.length} reviews" %></span>
        </div>
      </a>
    <% end %>
  </div>
  
</div>


<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/hackatools/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/products/new.html.erb
<div class="container-fluid">
	<h1>New product</h1>

	<%= render 'form' %>

	<%= link_to 'Back', products_path, class: 'btn btn-link' %>
</div>

app/views/products/search.html.erb
<div class="container-fluid">
  <% if @products.empty? %>
    <h3>Oops! There's no product found! Would you like to add one?</h3>
  <% else %>
    <% @products.each do |product| %>
      <a href=<%= product_path(product) %> class="item"><div class="item__logo"><%= image_tag product.image_url %></div><h4><%= product.name %></h4><div class="stars-container"><div class="star-rating" data-score=<%= product.avg_rating %> ></div> <span><%= "#{product.reviews.length} reviews" %></span></div></a>
    <% end %>
  <% end %>
</div>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/hackatools/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/products/show.html.erb
<div class="product-hdr">
	<a href=<%= @product.website %> class="item">
		<div class="item__logo">
			<%= image_tag @product.image_url %>
		</div>
	</a>
	<% if user_signed_in? && current_user.admin? %>
		<%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-link product-edit' %>
	<% end %>
	
	<p class="product__description"><%= @product.description %></p>

	<div class="product-rating">
		<div class="rating-readonly" data-score= <%= @avg_rating %> ></div>
		   <%= "#{@reviews.length} total reviews" %>
	</div>
	<div class="tags-container">
		<% @tags.each do |tag| %>
			<a href=<%= "/products/tag/#{CGI.escape tag}" %> class="tag"><%= tag %></a>
		<% end %>
	</div>
</div>

<div class="container-fluid">

	<div class="card-section" id="accordion" role="tablist" aria-multiselectable="true">
	  <div>
	    <div role="tab" id="headingOne">
	    	<a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" style="text-decoration:none;color:#333;">
		      <h3 style="margin:10px 0px;">
	          Product Description
		      </h3>
	      </a>
	    </div>
	    <div id="collapseOne" class="collapse out" role="tabpanel" aria-labelledby="headingOne">
	      <div class="">
	        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
	      </div>
	    </div>
	  </div>
	</div>






	<div class="row">
		<div class="col-md-8">
			<%= render 'review_list' %>
		</div>

		<div class="col-md-4">
			<%= render 'similar_products' %>
		</div>
	</div>
</div>


<script>
	$('.rating-readonly').raty({
		path: 'https://s3.amazonaws.com/hackatools/stars',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
	$('.rating-write').raty({
    path: 'https://s3.amazonaws.com/yelpdemo/stars',
    scoreName: 'review[ease_of_use_rating]'
  });
	// $('.rating-write__ease').raty({
 //    path: 'https://s3.amazonaws.com/yelpdemo/stars',
 //    scoreName: 'review[ease_of_use_rating]'
 //  });
  $('.review-rating').raty({
		path: 'https://s3.amazonaws.com/hackatools/stars',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
  // $('.rating-write__speed').raty({
  //   path: 'https://s3.amazonaws.com/yelpdemo/stars',
  //   scoreName: 'review[speed_of_dev_rating]'
  // });
</script>

app/views/products/tag.html.erb
<div class="container-fluid">
  <div class="tags-container">Product With Tags: <div class="tag"><%= @tag %></div></div>
  <div class="item-container">
    <% if @products.empty? %>
      <h3>Oops! There's no product found! Would you like to add one?</h3>
    <% else %>
      <% @products.each do |product| %>
        <a href=<%= product_path(product) %> class="item"><div class="item__logo"><%= image_tag product.image_url %></div><h4><%= product.name %></h4><div class="stars-container"><div class="star-rating" data-score=<%= product.avg_rating %> ></div> <span><%= "#{product.reviews.length} reviews" %></span></div></a>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/hackatools/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>