config/routes.rb
Hackatools::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  resources :products do 
    collection do
      get 'search'
      get 'tag/:tag', to: 'products#tag'
    end
    resources :reviews, except: [:show, :index]  
  end

  get "pages/about"
  get "pages/contact"
  get "pages/profile"

  root 'products#index'

end

app/views/layouts/_footer.html.erb
<div class="container-fluid footer">
	<p><h3 style="display: inline;">HackATools</h3> Copyright &copy; 2015</p>
	<p>Questions or Comments? Our email address is admin@hackatools.com</p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'HackATools', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag search_products_path, method: :get, class: "navbar-form navbar-left" do %>
          <p>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Search Product' %>
            <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
          </p>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% if current_user.admin? %>
            <li><%= link_to "", new_product_path, class: "glyphicon glyphicon-plus" %></li>
          <% end %>
        <% else %>
          <li><%= link_to 'Sign in', user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="categories-nav">
  <ul class="container-fluid">
    <li><a href="/products/tag/product">PRODUCT</a></li>
    <li><a href="/products/tag/design">DESIGN</a></li>
    <li><a href="/products/tag/development">DEVELOPMENT</a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackatools</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <main>
    <%= render 'layouts/navbar' %>

    <% flash.each do |name, msg| %>
    <div class="container-fluid">
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      </div>
    <% end %> 
    <%= yield %>
    
  </main>
  <%= render 'layouts/footer' %>
</body>
</html>